swagger: "2.0"
info:
  version: "0.5.0"
  title: "Dataverse TDR Bridge"
  description: "Archiving Dataverse dataset to Trust Digital Repository (TDR) by ingesting to SWORD2 endpoint."
  contact:
    email: "eko.indarto@dans.knaw.nl"
host: "localhost:8080"
basePath: "/api"
tags:
- name: TDR target
  description: "Trust Digital Repositories"
- name: "archiving"
  description: "Archive-related operation of datasets of Dataverse."
schemes:
- "http"
produces:
  - application/json
paths:
  /archive/state:
    get:
      tags:
      - "archiving"
      summary: "Operation to retrive a state of an Archived dataset"
      description: "Operation to retrive a state of an Archived dataset by filtering pid, version, tdr target."
      operationId: "getState"
      produces:
      - application/json
      parameters:
      - in: "query"
        name: "srcXml"
        required: true
        type: string
      - in: "query"
        name: "srcVersion"
        required: true
        type: string
      - in: "query"
        name: "targetIri"
        required: true
        type: string
      responses:
        '200':
          description: Plugin response
          schema:
            $ref: '#/definitions/Archived'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /archive/get-all:
    get:
        tags:
        - "archiving"
        summary: "peration to retrive all Archived datasets"
        description: "Operation to retrive all Archived datasets"
        operationId: "getAll"
        produces:
        - application/json
        responses:
          '200':
            description: Plugin response
            schema:
              type: array
              items:
                $ref: '#/definitions/Archived'
          default:
            description: unexpected error
            schema:
              $ref: '#/definitions/Error'

  /archive/create:
    post:
      tags:
      - "archiving"
      summary: "Operation to create a new Archive"
      description: "Add a new archive to TDR"
      operationId: "createArchive"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "ingestData"
        description: "Dataset object that needs to be added to the Archived's table."
        required: true
        schema:
          $ref: '#/definitions/IngestData'
      responses:
        '201':
          description: Dataset succesfully created.
          schema:
            $ref: '#/definitions/Archived'
        '400':
          description: Dataset couldn't have been created.
        '405':
          description: "Invalid input"

  /archive/{id}:
    delete:
      tags:
        - "archiving"
      summary: "Deletes a record"
      description: ""
      operationId: "deleteById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "api_key"
          in: "header"
          required: true
          type: "string"
        - name: "id"
          in: "path"
          description: "Record id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Record is deleted"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Record not found"
  /archive:
    delete:
      tags:
        - "archiving"
      summary: "Deletes a record"
      description: ""
      operationId: "deleteByParams"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "api_key"
          in: "header"
          required: true
          type: "string"
        - in: "query"
          name: "srcXml"
          required: true
          type: string
        - in: "query"
          name: "srcVersion"
          required: true
          type: string
        - in: "query"
          name: "targetIri"
          required: true
          type: string
      responses:
        200:
          description: "Record is deleted"
        400:
          description: "Invalid Paramas supplied"
        404:
          description: "Record not found"
    put:
      tags:
      - archiving
      summary: Updated Archive
      description: Update the existing Archive.
      operationId: updateArchive
      produces:
      - application/json
      - application/xml
      parameters:
        - name: "api_key"
          in: "header"
          required: true
          type: "string"
        - in: body
          name: archive
          description: Updated archive object
          required: true
          schema:
            $ref: '#/definitions/Archived'
      responses:
        200:
          description: "Record is updated"
        400:
          description: Invalid id supplied
        404:
          description: Archived not found
definitions:

  Archived:
    required:
      - srcXml
      - targetIri
    properties:
      id:
        type: integer
        format: int64
      srcXml:
        type: string
      srcVersion:
        type: string
      targetIri:
        type: string
      doi:
        type: string
      startTime:
        type: string
        format: date
      endTime:
        type: string
        format: date
      landingPage:
        type: string
      state:
        type: string
        enum:
          - IN-PROGRESS
          - FAILED
          - ARCHIVED

  SrcData:
    required:
      - srcXml
      - srcVersion
      - appName
    properties:
      srcXml:
        type: string
        description: exported xml link
      srcVersion:
        type: string
      appName:
        type: string
      apiToken:
        type: string
        description: Api Token is optional

  TdrData:
    required:
      - username
      - password
      - iri
      - appName
    properties:
      username:
        type: string
      password:
        type: string
      appName:
        type: string
      iri:
        type: string

  IngestData:
    required:
      - srcData
      - tdrData
    properties:
      srcData:
        $ref: '#/definitions/SrcData'
      tdrData:
        $ref: '#/definitions/TdrData'

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string